Project is being updated to the point that is all automated. Each house page is opened and the data is collected from the page.
Error: balcony value gives error and bathroom value seems to be empty